FizzBuzz問題の提出課題
NorifumiOgawa/ruby-practices pull request #1
Opened 2021-06-11 01:07 UTC by NorifumiOgawa

PullRequest先を自分のリモートリポジトリにしました。
よろしくお願い致します。

2021-06-11 04:44 UTC, komagata requested changes

2021-06-11 04:44 UTC, komagata commented on 01.fizzbuzz/fizzbuzz.rb
> +
ここに不要な空行があるみたいです〜

2021-06-11 05:24 UTC, NorifumiOgawa commented on 01.fizzbuzz/fizzbuzz.rb
> +
@komagata 空行を削除して再度pushしました！

2021-06-12 05:13 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-06-27 06:45 UTC, merged